<wsdl:definitions
     name="customerChecks_dbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentEnablement_SOA/CustomerValidationService/customerChecks_dbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentEnablement_SOA/CustomerValidationService/customerChecks_dbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/customerChecks_dbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="customerChecks_dbReference_plt" >
    <plt:role name="customerChecks_dbReference_role" >
      <plt:portType name="tns:customerChecks_dbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/customerChecks_dbReference" schemaLocation="../Schemas/customerChecks_dbReference_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="selectByPrimaryKey_inputParameters">
        <wsdl:part name="selectByPrimaryKey_inputParameters" element="top:CustomerChecksPrimaryKey"/>
    </wsdl:message>
    <wsdl:message name="CustomerChecksCollection_msg">
        <wsdl:part name="CustomerChecksCollection" element="top:CustomerChecksCollection"/>
    </wsdl:message>
    <wsdl:portType name="customerChecks_dbReference_ptt">
        <wsdl:operation name="selectByPrimaryKey">
            <wsdl:input message="tns:selectByPrimaryKey_inputParameters"/>
            <wsdl:output message="tns:CustomerChecksCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
