<wsdl:definitions
     name="Poll_N_Delete_OldPaymentRequest"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentEnablement_SOA/InvalidateOldPaymentRequests/Poll_N_Delete_OldPaymentRequest"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentEnablement_SOA/InvalidateOldPaymentRequests/Poll_N_Delete_OldPaymentRequest"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/Poll_N_Delete_OldPaymentRequest"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="Poll_N_Delete_OldPaymentRequest_plt" >
    <plt:role name="Poll_N_Delete_OldPaymentRequest_role" >
      <plt:portType name="tns:Poll_N_Delete_OldPaymentRequest_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="Poll_N_Delete_OldPaymentRequest_plt" >
    <plt:role name="Poll_N_Delete_OldPaymentRequest_role" >
      <plt:portType name="tns:Poll_N_Delete_OldPaymentRequest_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Poll_N_Delete_OldPaymentRequest" schemaLocation="../Schemas/Poll_N_Delete_OldPaymentRequest_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="PaymentReqTransCollection_msg">
        <wsdl:part name="PaymentReqTransCollection" element="top:PaymentReqTransCollection"/>
    </wsdl:message>
    <wsdl:portType name="Poll_N_Delete_OldPaymentRequest_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:PaymentReqTransCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
