<wsdl:definitions
     name="UpdateLogicalDelete"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentEnablement_SOA/InvalidateOldPaymentRequests/UpdateLogicalDelete"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentEnablement_SOA/InvalidateOldPaymentRequests/UpdateLogicalDelete"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateLogicalDelete"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="UpdateLogicalDelete_plt" >
    <plt:role name="UpdateLogicalDelete_role" >
      <plt:portType name="tns:UpdateLogicalDelete_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateLogicalDelete" schemaLocation="../Schemas/UpdateLogicalDelete_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="PaymentReqTransCollection_msg">
        <wsdl:part name="PaymentReqTransCollection" element="top:PaymentReqTransCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateLogicalDelete_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:PaymentReqTransCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
